# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKBG0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_date', models.DateField()),
                ('stockname', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('industry', models.TextField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('ai_date',),
            },
        ),
    ]
