# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_stockkbg0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockKBG0',
            new_name='StockG0',
        ),
    ]
