# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170907_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockG0',
            new_name='Stock0',
        ),
        migrations.AlterModelOptions(
            name='stock0',
            options={'ordering': ('-ai_date',)},
        ),
    ]
