# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20170907_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock0',
            name='industry',
            field=models.CharField(max_length=30),
        ),
    ]
